language: go

go:
  - 1.2
  - 1.3
  - tip
install:
  - go get github.com/stretchr/testify/assert
  - go get code.google.com/p/goauth2/oauth
  - go get github.com/bitly/go-simplejson
  - go get github.com/mitchellh/mapstructure
