// This file was generated by counterfeiter
package rpcTests

import (
	"sync"

	"github.com/cryptix/trakting/types"
)

type FakeUserer struct {
	AddStub        func(name, passw string, level int) error
	addMutex       sync.RWMutex
	addArgsForCall []struct {
		name  string
		passw string
		level int
	}
	addReturns struct {
		result1 error
	}
	ChangePasswordStub        func(id int64, newpw string) error
	changePasswordMutex       sync.RWMutex
	changePasswordArgsForCall []struct {
		id    int64
		newpw string
	}
	changePasswordReturns struct {
		result1 error
	}
}

func (fake *FakeUserer) Add(name string, passw string, level int) error {
	fake.addMutex.Lock()
	fake.addArgsForCall = append(fake.addArgsForCall, struct {
		name  string
		passw string
		level int
	}{name, passw, level})
	fake.addMutex.Unlock()
	if fake.AddStub != nil {
		return fake.AddStub(name, passw, level)
	} else {
		return fake.addReturns.result1
	}
}

func (fake *FakeUserer) AddCallCount() int {
	fake.addMutex.RLock()
	defer fake.addMutex.RUnlock()
	return len(fake.addArgsForCall)
}

func (fake *FakeUserer) AddArgsForCall(i int) (string, string, int) {
	fake.addMutex.RLock()
	defer fake.addMutex.RUnlock()
	return fake.addArgsForCall[i].name, fake.addArgsForCall[i].passw, fake.addArgsForCall[i].level
}

func (fake *FakeUserer) AddReturns(result1 error) {
	fake.AddStub = nil
	fake.addReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeUserer) ChangePassword(id int64, newpw string) error {
	fake.changePasswordMutex.Lock()
	fake.changePasswordArgsForCall = append(fake.changePasswordArgsForCall, struct {
		id    int64
		newpw string
	}{id, newpw})
	fake.changePasswordMutex.Unlock()
	if fake.ChangePasswordStub != nil {
		return fake.ChangePasswordStub(id, newpw)
	} else {
		return fake.changePasswordReturns.result1
	}
}

func (fake *FakeUserer) ChangePasswordCallCount() int {
	fake.changePasswordMutex.RLock()
	defer fake.changePasswordMutex.RUnlock()
	return len(fake.changePasswordArgsForCall)
}

func (fake *FakeUserer) ChangePasswordArgsForCall(i int) (int64, string) {
	fake.changePasswordMutex.RLock()
	defer fake.changePasswordMutex.RUnlock()
	return fake.changePasswordArgsForCall[i].id, fake.changePasswordArgsForCall[i].newpw
}

func (fake *FakeUserer) ChangePasswordReturns(result1 error) {
	fake.ChangePasswordStub = nil
	fake.changePasswordReturns = struct {
		result1 error
	}{result1}
}

var _ types.Userer = new(FakeUserer)
